### ISSUE TITLE
Allow different content types

### ISSUE THREAD

**Issue by yadavsaroj** [pact-foundation/pact-mock_service#32]
Hey there!

I am thinking of using pact-mock_service with a microservice that accepts Avro JSON and binary data. Looks like currently pact-mock_service only support JSON data. I am curious about your thoughts on extending it to support different content types?

Best!
Saroj

**Comment by bethesque** [comment]
You will need to implement a differ (this generates a diff) and a diff formatter (this displays the diff in a meaningful way) and set these based on the content type.
Copy the code example here: https://github.com/bethesque/pact-xml

**Comment by yadavsaroj** [comment]
Thanks! I will take a look.

**Comment by mboudreau** [comment]
Can confirm this issue because of this line of code: https://github.com/bethesque/pact-mock_service/blob/master/lib/pact/mock_service/request_handlers/interaction_replay.rb#L16

It will fail if it's not JSON.  We were trying to use it to check a binary upload, but we're not matching on the body, only the headers of the requests which I feel should still work.

**Comment by bethesque** [comment]
It works with text/plain content type, so that line should not be an issue.
This question has been asked so many times, that I've finally written it up
in the wiki and added it to the FAQ.

https://github.com/realestate-com-au/pact/wiki/How-to-extend-Pact-for-different-content-types

Michel, if there's somewhere else that this content belongs now, let me
know.

**Comment by mboudreau** [comment]
The problem I see is that people using pact aren't particularly using Ruby.
In this case, it's all node and they're so abstracted to the Ruby binary
that there's no way to change the configuration of it or make it scalable
within the business.

I'm not asking to create diffs for all the different content types, in this
case, the only contract is through the http headers, but it still fails if
the body isn't utf8, even though no matching is to be done. We should be
able to at least not make it crash.

**Comment by bethesque** [comment]
Hm. There was a reason for the UTF-8, but I can't remember it now. If
someone wants to work on this, it shouldn't be too hard.

Sigh... baby number 1 calls...

**Comment by YOU54F** [comment]
The recommend way now to support alternative content types is building your own pact plugin

https://docs.pact.io/plugins/quick_start

This is possible with the current rust mock server library/cli built in rust

https://github.com/pact-foundation/pact-core-mock-server

pact avro plugin is here

https://github.com/austek/pact-avro-plugin

examples of interop with the pact ffi library to use plugins are shown here

https://github.com/YOU54F/pact-ruby-ffi
